version: '3.4'

services:
  clinimedauthserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    image: ${DOCKER_REGISTRY-}clinimedauthserver
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  web:
    build:
      context: ./AccountServices
      dockerfile: Dockerfile.yaml
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./AccountServices:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile.yaml
    volumes:
      - ./FrontEnd:/srv/app
    ports:
      - "8080:8080"
    image: node:12
    working_dir: /srv/app
    command: 'npm run serve'


  db:
    build:
      dockerfile: ./docker/Dockerfile.pgsql
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
     image: redis

volumes:
  db_data: {}
